import {
  BatteryIcon1,
  BatteryIcon2,
  FuelIcon1,
  FuelIcon2,
  FuelIcon3,
} from '../assets/svg';
import {moderateScale} from '../common/constants';
import strings from '../i18n/strings';
import {colors} from '../themes';

const iconScale = moderateScale(20);

export const traceListData = [
  {
    id: 1,
    vNo: 'KA02HG1786',
    desc: 'MAT788052P7C06674',
    energy: '12.5V',
    status: strings.running,
    title: '20kmph',
    color: colors.textColor6,
    batteryIcon: <BatteryIcon1 height={iconScale} width={iconScale} />,
    fuelIcon: <FuelIcon1 height={iconScale} width={iconScale} />,
  },
  {
    id: 2,
    vNo: 'KA02HG1547',
    desc: 'MAT788052P7C06674',
    energy: '12.5V',
    status: strings.idle,
    title: '20 mins',
    color: colors.textColor7,
    batteryIcon: <BatteryIcon2 height={iconScale} width={iconScale} />,
    fuelIcon: <FuelIcon2 height={iconScale} width={iconScale} />,
  },
  {
    id: 3,
    vNo: 'KA02HG1287',
    desc: 'MAT788052P7C06674',
    energy: '12.5V',
    status: strings.halt,
    title: '20 mins',
    color: colors.textColor8,
    batteryIcon: <BatteryIcon1 height={iconScale} width={iconScale} />,
    fuelIcon: <FuelIcon3 height={iconScale} width={iconScale} />,
  },
  {
    id: 4,
    vNo: 'KA02HG1589',
    desc: 'MAT788052P7C06701',
    energy: '12.3V',
    status: strings.running,
    title: '30kmph',
    color: colors.textColor6,
    batteryIcon: <BatteryIcon1 height={iconScale} width={iconScale} />,
    fuelIcon: <FuelIcon1 height={iconScale} width={iconScale} />,
  },
  {
    id: 5,
    vNo: 'KA02HG1390',
    desc: 'MAT788052P7C06702',
    energy: '11.9V',
    status: strings.idle,
    title: '15 mins',
    color: colors.textColor7,
    batteryIcon: <BatteryIcon1 height={iconScale} width={iconScale} />,
    fuelIcon: <FuelIcon1 height={iconScale} width={iconScale} />,
  },
  {
    id: 6,
    vNo: 'KA02HG1671',
    desc: 'MAT788052P7C06703',
    energy: '12.7V',
    status: strings.halt,
    title: '50 mins',
    color: colors.textColor8,
    batteryIcon: <BatteryIcon1 height={iconScale} width={iconScale} />,
    fuelIcon: <FuelIcon1 height={iconScale} width={iconScale} />,
  },
  {
    id: 7,
    vNo: 'KA02HG1822',
    desc: 'MAT788052P7C06704',
    energy: '13.0V',
    status: strings.running,
    title: '25kmph',
    color: colors.textColor6,
    batteryIcon: <BatteryIcon1 height={iconScale} width={iconScale} />,
    fuelIcon: <FuelIcon1 height={iconScale} width={iconScale} />,
  },
  {
    id: 8,
    vNo: 'KA02HG1453',
    desc: 'MAT788052P7C06705',
    energy: '12.4V',
    status: strings.idle,
    title: '10 mins',
    color: colors.textColor7,
    batteryIcon: <BatteryIcon1 height={iconScale} width={iconScale} />,
    fuelIcon: <FuelIcon1 height={iconScale} width={iconScale} />,
  },
];
